# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lavnok
email: contact@lavnok.com
description: > # this means to ignore newlines until "baseurl:"
  Lots of sky.. Come, let's fly..

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.lavnok.com" # the base hostname & protocol for your site
twitter_handle: lavnok
github_username:  lavnok
facebook_page: TeamLavnok
future: true

# Page Level settings
permalink: /posts/:title

# Style settings
sass:
    style: compressed

# Build settings
markdown: kramdown
